# Generated by Django 4.2.3 on 2023-07-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opanahub', '0002_alter_profile_back_img_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='back_img',
            field=models.ImageField(default='thin.jpg', upload_to='back_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='blank.webp', upload_to='profile_images'),
        ),
    ]
